### ISSUE TITLE
crash when opening file dialoge

### ISSUE THREAD

**Issue by ford--prefect** [tobimensch/aqemu#1]
aqemu0.9 is crashing consistently on an up-to-date archlinux system.

Steps to reproduce:
1) wipe ~/.aqemu folder
2) open aqemu
3) add new image (green + sign)
4) change to HDD tab
5) press button for filesystem browsing (folder image)
-> instant crash.

full gdb backtrace at http://pastebin.com/eRt5k9XW

**Comment by tobimensch** [comment]
I have a hunch what the problem is. I will hopefully be able to do a bugfix release soon.

**Comment by tobimensch** [comment]
Yeah, the problem is related to KDE. I don't get that crash on gnome-shell. The problem probably is this: I created a wrapper for QDom* (because it's not officially supported by Qt anymore => deprecated), but KDE apparently still uses the old QtXML libraries. Now the QDom* wrapper and QtXML are getting in conflict with each other, because the KDE libraries are dynamically linked at runtime for the filemanager (to make it look more integrated). I will try to put my wrapper into a different namespace to avoid conflicts.

I just installed KDE and tried to reproduce this bug, but so far could not do so. I also don't seem to get that fancy KDE filedialog. Do you have any extra libraries installed for that purpose (getting KDE filedialog in Qt apps)?

I just commited the likely fix to the repository. Unfortunately I can't test, so your help would be greatly appreciated.

**Comment by ford--prefect** [comment]
just create a branch with the possible fix and i can test it locally in my kde environment.

**Comment by tobimensch** [comment]
I already commited it to master. Even if it's not the fix, it's definitely best practice to put something like that in a namespace.

**Comment by tobimensch** [comment]
Forgot to push it. :-( Now you can test it.

**Comment by tobimensch** [comment]
I was able to reproduce it myself now. And it looks like the last commit fixed the issue. Waiting for you to confirm.

**Comment by ford--prefect** [comment]
it works for me as well. i guess closing this is appropriate?
