### ISSUE TITLE
Section titles don't follow theme colors

### ISSUE THREAD

**Issue by gavsiu** [tobimensch/aqemu#16]
Machine, General, Devices, Network, etc stay at the ugly blue color. Can we have them respect theme colors?

**Comment by tobimensch** [comment]
Hmm, seems to me like this is a matter of preference. The answer is yes, I would have to add an option for that.

For me and the Qt-gtk theme I'm using the colors look good. If it would be just another black color, the contrast between headings and the text under the headings would look "weaker".

Just so you know why those colors currently are how they are.

I also made those colors the same in the Info and VM tabs, to have some conformity in the look.

However, of course it would be possible to simply use the theme colors, I'm just not sure I want that to be the default.

I'd also like to know what others think.

gavsiu, can you send me a screenshot of AQEMU with your theme, so that I can see what exactly the problem is for you? (Maybe you've  a theme where the blue colors look worse than on what I've tested so far)

Of course it wouldn't be a problem to add an option.

Again, the idea is to visually separate sections. If all fonts are just black(or whatever the theme font color is), then I feel some clarity in the UI may be lost.

So @gavsiu do you have another idea for strongly seperating sections, since you don't want to allow/accept a distinctive color?

Would it be better for you if the color was derived from your theme, in example a link color?

**Comment by gavsiu** [comment]
![scrot](http://i.imgur.com/MvxU6Fo.png)

Since the font weight is the same, I think the blue should just follow the white however it's coded. I'm using Arc-Darker.

**Comment by tobimensch** [comment]
Thanks! Now I can see what the issue is. I'm not using a dark theme. Looking at your screenshot I must agree that the blue looks ugly in combination with that theme. I'll probably change this by detected a dark theme (somehow) and then using an appropriate color, either the a color from the theme or another color that looks good on a dark background. Do you have any comments on what colors would be acceptable?

**Comment by tobimensch** [comment]
@gavsiu: Actually AQEMU respected theme colors all along.

AQEMU is using the QPalette.link color in this case, which looks okay to me
in the Breeze Dark theme I just tested.
However in the dark theme you're using it doesn't look good at all.

Which brings me to the following questions:

1) What is the name of the dark theme you're using?

2) What version of that theme are you using?

3) What are your KDE5 and Qt5 versions?

**Comment by tobimensch** [comment]
@gavsiu:

I made an attempt to fix this.

I commited the fix to the service_branch, which is the current development branch.

git clone https://github.com/tobimensch/aqemu.git
cd aqemu
git branch service_branch
cmake .
make -j4
make install

Please see, if this fixed the issue for you and tell me!

Then I can close the issue and the fix will land in 0.9.3.

**Comment by gavsiu** [comment]
I've been waiting to reply because I was reinstalling my Arch. Running the above, but I'm getting this:

    $ cmake .
    -- MAN page will be installed is not packed.
    -- MAN_PAGE_COMPRESSOR flag not set. Available values: gzip, bzip2, lzma
    -- Will be installed not compressed MAN pages
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    LIBVNCCLIENT_LIBRARIES
        linked by target "aqemu" in directory /home/gavsiu/build-repos/aqemu
    
    -- Configuring incomplete, errors occurred!
    See also "/home/gavsiu/build-repos/aqemu/CMakeFiles/CMakeOutput.log".

**Comment by tobimensch** [comment]
Is libvncclient / libvncserver installed?

Make sure you rm -rf aqemu/ before you start, to make
sure you start from a clean slate.

**Comment by tobimensch** [comment]
FYI, I merged the service_branch back into master. So git checkout service_branch will not work anymore.

**Comment by gavsiu** [comment]
All fixed.
