### ISSUE TITLE
Support for qemu-arm or other arch's supported by qemu

### ISSUE THREAD

**Issue by redbrain** [tobimensch/aqemu#8]
Just wondering if any plans or desires to support the more esoteric arch's of qemu. I know they are slow but might be interesting to see how that plays out in a ui for ease of use and setup.

**Comment by tobimensch** [comment]
They should be supported. But you need to have the according qemu binaries installed first. For example qemu-system-x86_64 is obviously for x86_64 (and kvm).

Make sure qemu-system-arm is installed. If you install it, you have to go to File->Configuration->QEMU and redetect qemu (so it can update the options).

Then select TCG instead of KVM as the accelerator (KVM is only for x86_64) and it should list ARM as available architecture.

**Comment by redbrain** [comment]
Thats fantastic! Great project for embedded development or os development. People tend to use bochs or qemu scripts which is annoying sometimes.
